# Generated by Django 3.2.5 on 2021-07-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210709_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneImages',
            new_name='PhoneImage',
        ),
    ]
